// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TowBoatSalvageWebApp.Data;

#nullable disable

namespace TowBoatSalvageWebApp.Migrations.SalvageDb
{
    [DbContext(typeof(SalvageDbContext))]
    [Migration("20260301191430_WorkOrderModel")]
    partial class WorkOrderModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("TowBoatSalvageWebApp.Data.FuelLogEntry", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BoatName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CrewMember")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Engine1Hours")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Engine2Hours")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Fuel1")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Fuel2")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GasCans")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("BoatName", "LogDate");

                    b.ToTable("FuelLogs");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.DocumentSignatureRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("AuditTrail")
                        .HasColumnType("BLOB");

                    b.Property<string>("CaptainEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CaptainName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Delivery")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GPS")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Quote")
                        .HasColumnType("TEXT");

                    b.Property<string>("SalvagePricingModel")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SentAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Signature")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SignedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignedByName")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("SignedPdf")
                        .HasColumnType("BLOB");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnaccompaniedDestination")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnaccompaniedOrigin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Underwriter")
                        .HasColumnType("TEXT");

                    b.Property<string>("VesselLength")
                        .HasColumnType("TEXT");

                    b.Property<string>("VesselMakeModel")
                        .HasColumnType("TEXT");

                    b.Property<string>("VesselName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("DocumentSignatureRequests");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.SalvageCell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColumnId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ColumnId");

                    b.HasIndex("RowId", "ColumnId")
                        .IsUnique();

                    b.ToTable("Cells");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.SalvageColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Columns");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.SalvageFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CellId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CellId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.SalvageRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Rows");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.TowBoatCaptains", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Captains");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.TowBoatPorts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Ports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Tampa Bay",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Gulfport",
                            SortOrder = 1
                        });
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.WorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrectionNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Engine1Hours")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Engine2Hours")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAddingCorrection")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("ReportedIssues")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestDateDisplay")
                        .HasColumnType("TEXT");

                    b.Property<string>("VesselName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WorkOrder");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.SalvageCell", b =>
                {
                    b.HasOne("TowBoatSalvageWebApp.Models.SalvageColumn", "Column")
                        .WithMany("Cells")
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TowBoatSalvageWebApp.Models.SalvageRow", "Row")
                        .WithMany("Cells")
                        .HasForeignKey("RowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Column");

                    b.Navigation("Row");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.SalvageFile", b =>
                {
                    b.HasOne("TowBoatSalvageWebApp.Models.SalvageCell", "Cell")
                        .WithMany("Files")
                        .HasForeignKey("CellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cell");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.SalvageCell", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.SalvageColumn", b =>
                {
                    b.Navigation("Cells");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.SalvageRow", b =>
                {
                    b.Navigation("Cells");
                });
#pragma warning restore 612, 618
        }
    }
}
