// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TowBoatSalvageWebApp.Data;

#nullable disable

namespace TowBoatSalvageWebApp.Migrations.SalvageDb
{
    [DbContext(typeof(SalvageDbContext))]
    [Migration("20260816012008_AddEngineHoursToVesselInspection")]
    partial class AddEngineHoursToVesselInspection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("TowBoatSalvageWebApp.Data.FuelLogEntry", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BoatName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CrewMember")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Engine1Hours")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Engine2Hours")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Fuel1")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Fuel2")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GasCans")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("BoatName", "LogDate");

                    b.ToTable("FuelLogs");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.CaptainsPersonalItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoInflateLifeJacket")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AutoInflateLifeJacketExpires")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CaptainsDitchBag")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CaptainsUSCGLicence")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ClipboardsWithInvoices")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DrugConsortiumExpires")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PLBBatteryRegistration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PLBExpires")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ProofOfDrugConsortium")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("USCGLicenseExpires")
                        .HasColumnType("TEXT");

                    b.Property<bool>("USCGRulesOfTheRoadBook")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CaptainsPersonalItems");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.CreditCard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorizedAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("CVV")
                        .HasColumnType("TEXT");

                    b.Property<string>("CardHolderName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CardNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Expiration")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CreditCard");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.DocumentSignatureRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("AuditTrail")
                        .HasColumnType("BLOB");

                    b.Property<string>("CaptainEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CaptainName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimNumber")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreditCardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Delivery")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EmailAcceptedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EmailDeliveredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EmailFailedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailFailureReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailLastEvent")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EmailOpenedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GPS")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Quote")
                        .HasColumnType("TEXT");

                    b.Property<string>("SalvagePricingModel")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SentAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Signature")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SignedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignedByName")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("SignedPdf")
                        .HasColumnType("BLOB");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnaccompaniedDestination")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnaccompaniedOrigin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Underwriter")
                        .HasColumnType("TEXT");

                    b.Property<string>("VesselLength")
                        .HasColumnType("TEXT");

                    b.Property<string>("VesselMakeModel")
                        .HasColumnType("TEXT");

                    b.Property<string>("VesselName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreditCardId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("DocumentSignatureRequests");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.Honda500Hr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BoatNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCompleted")
                        .HasColumnType("TEXT");

                    b.Property<int>("EngineHours1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EngineHours2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("bHasBeenDownloaded")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("bIsResolved")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Honda500HrServices");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.InitialInspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AlcoholTestStrip")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AlcoholTestStripDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CurrentRegistration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FloridaDOCCertificate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FloridaRegistration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("VesselsLogBook")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("InitialInspection");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.MountedLights", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DeckFlood")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Flashlight")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FogHorn")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Hailer")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Horn")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Navigation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PublicSafety")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Siren")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SpotLight")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Towing")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MountedLights");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.Navigation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BackupGPS")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Binoculars")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CheckDVRCardForRecording")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DVR")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DepthFinder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FirstRecording")
                        .HasColumnType("TEXT");

                    b.Property<bool>("GPS")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastRecording")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Radar")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("VHFPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("VHFSecondary")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WhiskeyOrELectronicCompass")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Navigation");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.Oil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FourCycleOil")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TwoStrokOil")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Oil");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.OperationalCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateOfPumpCheck")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmptyFuelCarburator")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FillGasTank")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InspectWiring")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SalvagePump")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ServicePump")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("VerifyPumpRuns")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("OperationalCheck");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.PaymentRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("CaptainEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CaptainName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EmailAcceptedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EmailDeliveredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EmailFailedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailFailureReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailLastEvent")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EmailOpenedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailTrackingToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StripePaymentLinkId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StripePaymentLinkUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StripeReceiptUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("StripeSessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StripePaymentLinkId");

                    b.ToTable("PaymentRequests");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.Placards", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BoatUSMembershipApplications")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DischargeOfGarbage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DischargeOfOil")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NavigationChart")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Placards");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.SafetyDevices", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AdultPFDs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CaptainCrewType1Offshore")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ChildsPFDs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ColdWaterSuite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Epirb")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EpirbExpires")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FireExtinguishers")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FirstAidKit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Flares")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FlaresExpire")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HandheldVHF")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ThermalBlanket")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ThrowableLifeRing")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SafetyDevices");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.Salvage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Bucket")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FoamFootballs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PVCPipe")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Pads")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Pump")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SuctionHose")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TwoRulePumps")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WoodenPlugs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Salvage");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.SalvageCell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColumnId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ColumnId");

                    b.HasIndex("RowId", "ColumnId")
                        .IsUnique();

                    b.ToTable("Cells");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.SalvageColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Columns");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.SalvageFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CellId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CellId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.SalvageRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Rows");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.ServiceDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Honda500HrId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("bServiceCompleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Honda500HrId");

                    b.ToTable("ServiceDescription");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.ServiceDescriptionVesselInspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateForThisItem")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FirstRecording")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SecondRecording")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VesselInspectionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("bServiceCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("bThisItemRequiresDate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VesselInspectionId");

                    b.ToTable("ServiceDescriptionVesselInspection");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.TowBoatCaptains", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Captains");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.TowBoatPorts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Ports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Tampa Bay",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Gulfport",
                            SortOrder = 1
                        });
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.VehicleInspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaptainsPersonalItemsId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateOfInspection")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeOrCaptain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InitialInspectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MountedLightsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NavigationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OilId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OperationalCheckId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlacardsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SafetyDevicesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SalvageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VesselEquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VesselNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("bHasBeenDownloaded")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CaptainsPersonalItemsId");

                    b.HasIndex("InitialInspectionId");

                    b.HasIndex("MountedLightsId");

                    b.HasIndex("NavigationId");

                    b.HasIndex("OilId");

                    b.HasIndex("OperationalCheckId");

                    b.HasIndex("PlacardsId");

                    b.HasIndex("SafetyDevicesId");

                    b.HasIndex("SalvageId");

                    b.HasIndex("VesselEquipmentId");

                    b.ToTable("VehicleInspection");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.VesselEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BackupAnchor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BoatHook")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FendersTwo8")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FourDockLines")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("JumperCables")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Knife")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PrimaryAnchor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PrimaryTowLine")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SecondaryTowLine")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SpareBattery")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ToolKit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TowBit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TwoBilgePumps")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TwoFuelFilters")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TwoGasolineCans")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("VesselEquipment");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.VesselInspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BoatNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfInspection")
                        .HasColumnType("TEXT");

                    b.Property<int>("Engine1Hours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Engine2Hours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("bHasBeenDownloaded")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("bIsResolved")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("VesselInspection");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.WorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrectionNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Engine1Hours")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Engine2Hours")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FromCrewMember")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAddingCorrection")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IssueCorrectionThreads")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("IssueCorrections")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("IssueCorrectionsBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("ReportedIssues")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RequestDateDisplay")
                        .HasColumnType("TEXT");

                    b.Property<string>("VesselName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("bHasBeenDownloaded")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WorkOrder");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.DocumentSignatureRequest", b =>
                {
                    b.HasOne("TowBoatSalvageWebApp.Models.CreditCard", "CreditCard")
                        .WithMany()
                        .HasForeignKey("CreditCardId");

                    b.Navigation("CreditCard");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.SalvageCell", b =>
                {
                    b.HasOne("TowBoatSalvageWebApp.Models.SalvageColumn", "Column")
                        .WithMany("Cells")
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TowBoatSalvageWebApp.Models.SalvageRow", "Row")
                        .WithMany("Cells")
                        .HasForeignKey("RowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Column");

                    b.Navigation("Row");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.SalvageFile", b =>
                {
                    b.HasOne("TowBoatSalvageWebApp.Models.SalvageCell", "Cell")
                        .WithMany("Files")
                        .HasForeignKey("CellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cell");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.ServiceDescription", b =>
                {
                    b.HasOne("TowBoatSalvageWebApp.Models.Honda500Hr", null)
                        .WithMany("ServiceDescriptions")
                        .HasForeignKey("Honda500HrId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.ServiceDescriptionVesselInspection", b =>
                {
                    b.HasOne("TowBoatSalvageWebApp.Models.VesselInspection", null)
                        .WithMany("ServiceDescriptions")
                        .HasForeignKey("VesselInspectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.VehicleInspection", b =>
                {
                    b.HasOne("TowBoatSalvageWebApp.Models.CaptainsPersonalItems", "CaptainsPersonalItems")
                        .WithMany()
                        .HasForeignKey("CaptainsPersonalItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TowBoatSalvageWebApp.Models.InitialInspection", "InitialInspection")
                        .WithMany()
                        .HasForeignKey("InitialInspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TowBoatSalvageWebApp.Models.MountedLights", "MountedLights")
                        .WithMany()
                        .HasForeignKey("MountedLightsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TowBoatSalvageWebApp.Models.Navigation", "Navigation")
                        .WithMany()
                        .HasForeignKey("NavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TowBoatSalvageWebApp.Models.Oil", "Oil")
                        .WithMany()
                        .HasForeignKey("OilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TowBoatSalvageWebApp.Models.OperationalCheck", "OperationalCheck")
                        .WithMany()
                        .HasForeignKey("OperationalCheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TowBoatSalvageWebApp.Models.Placards", "Placards")
                        .WithMany()
                        .HasForeignKey("PlacardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TowBoatSalvageWebApp.Models.SafetyDevices", "SafetyDevices")
                        .WithMany()
                        .HasForeignKey("SafetyDevicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TowBoatSalvageWebApp.Models.Salvage", "Salvage")
                        .WithMany()
                        .HasForeignKey("SalvageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TowBoatSalvageWebApp.Models.VesselEquipment", "VesselEquipment")
                        .WithMany()
                        .HasForeignKey("VesselEquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaptainsPersonalItems");

                    b.Navigation("InitialInspection");

                    b.Navigation("MountedLights");

                    b.Navigation("Navigation");

                    b.Navigation("Oil");

                    b.Navigation("OperationalCheck");

                    b.Navigation("Placards");

                    b.Navigation("SafetyDevices");

                    b.Navigation("Salvage");

                    b.Navigation("VesselEquipment");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.Honda500Hr", b =>
                {
                    b.Navigation("ServiceDescriptions");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.SalvageCell", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.SalvageColumn", b =>
                {
                    b.Navigation("Cells");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.SalvageRow", b =>
                {
                    b.Navigation("Cells");
                });

            modelBuilder.Entity("TowBoatSalvageWebApp.Models.VesselInspection", b =>
                {
                    b.Navigation("ServiceDescriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
